report_page/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name= 'logout'),
]

report_page/report_page/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('statistic.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

report_page/statistic/urls.py
from django.urls import path

from . import views

app_name = 'statistic'

urlpatterns = [
    path('', views.entry_list, name='index'),
    path('create/', views.create_entry, name='create_entry'),
    path('entry_detail/<int:id>/', views.get_entry, name='entry_detail'),
    path('delete/<int:id>', views.delete_entry, name='delete'),
    path('weekly/', views.weekly_stats, name='weekly'),
]

report_page/accounts/models.py
from django.db import models

# Create your models here.

report_page/statistic/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg, Count, Sum
from django.db.models.functions import ExtractWeek

class EntryManager(models.Manager):
    def get_weekly_stats(self, start_datetime, end_datetime, user):
        return self.filter(user=user, datetime__range=(start_datetime, end_datetime)).annotate(week=ExtractWeek('datetime')).values(
            'week').annotate(avg_speed=Avg('speed'), total_distance=Sum('distance'), total_duration=Sum('duration'), total_entries=Count('id'))


class Entry(models.Model):
    datetime = models.DateTimeField()
    distance = models.FloatField(db_index=True)
    duration = models.FloatField(db_index=True)
    speed = models.FloatField(db_index=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)+str(self.distance)+str(self.duration)+str(self.datetime)

    def save(self, *args, **kwargs):
        self.speed = self.distance/self.duration
        super().save(*args,**kwargs)

    stats = EntryManager()
    objects = models.Manager()

report_page/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class ReportUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(ReportUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

report_page/statistic/forms.py
from django import forms
from django.db.models import fields
from .models import Entry

class CreateEntryForm(forms.ModelForm):
    distance = forms.FloatField(min_value=0.001)
    duration = forms.FloatField(min_value=0.001)

    class Meta:
        model = Entry
        exclude = ['speed', 'user']

class DateInput(forms.DateInput):
    input_type = 'date'

class FilterForm(forms.Form):
    datetime_start=forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    datetime_end=forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))

    def clean_datetime_end(self):
        start_date = self.cleaned_data['datetime_start']
        end_date = self.cleaned_data['datetime_end']

        if end_date <= start_date:
            raise forms.ValidationError("End date must be later than start date")
        return end_date

report_page/accounts/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import  render, redirect
from .forms import ReportUserForm
from django.contrib.auth import login as auth_login, authenticate, logout as auth_logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm

def signup(request):
    if request.method == 'POST':
        form = ReportUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            messages.success(request, 'Registration successful.' )
            return redirect('/')
        messages.error(request, 'Unsuccessful registration. Invalid information.')
    form = ReportUserForm
    return render (request=request, template_name='accounts/signup.html', context={'signup_form':form})

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                messages.info(request, f'You are now logged in as {username}.')
                return redirect('/')
            else:
                messages.error(request,'Invalid username or password.')
        else:
            messages.error(request,'Invalid username or password.')
    form = AuthenticationForm()
    return render(request=request, template_name='accounts/login.html', context={'login_form':form})

def logout(request):
    auth_logout(request)
    messages.info(request, 'Logout successfully')
    return redirect('/')

report_page/statistic/views.py
from django.http import HttpResponse
from django.views import generic
from django.db.models import Avg, Count, Sum
from django.db.models.functions import ExtractWeek
from .models import Entry
from .forms import CreateEntryForm, FilterForm
import datetime
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages

@login_required
def weekly_stats(request):
    end_datetime = datetime.datetime.utcnow()
    start_datetime = end_datetime - datetime.timedelta(days=365)
    entries = Entry.stats.get_weekly_stats(start_datetime,end_datetime,request.user)
    context={'stats':entries}
    return render(request, 'statistic/weekly.html', context)


@login_required
def create_entry(request):
    if request.method == 'POST':
        entry = Entry(user=request.user)
        form = CreateEntryForm(request.POST, instance=entry)
        if form.is_valid():
            entry.save()
            form = CreateEntryForm()
            messages.info(request, 'Successful create')
    else:
        form = CreateEntryForm()
    context = {'form':form}
    return render(request, 'statistic/entry_create.html', context)

@login_required
def get_entry(request, **kwargs):
    entry_id = kwargs.get('id')
    entry = get_object_or_404(Entry, pk=entry_id)

    if request.method == "POST":
        form = CreateEntryForm(request.POST, instance=entry)
        if form.is_valid():
            form.save()
            messages.info(request, 'Successful update')
    else:
        form = CreateEntryForm(instance=entry)

    context = {'entry':entry, 'form': form}
    return render(request, 'statistic/entry_detail.html', context )

@login_required
def delete_entry(request, **kwargs):
    entry_id = kwargs.get('id')
    entry = Entry.objects.get(id=entry_id)
    entry.delete()
    messages.info(request, 'Successful delete')
    return redirect('statistic:index')

@login_required
def entry_list(request, **kwargs):
    form = FilterForm(request.POST)
    qs = None
    if form.is_valid():
        datetime_start=form.cleaned_data['datetime_start']
        datetime_end=form.cleaned_data['datetime_end']
        qs =  Entry.objects.filter(user=request.user, datetime__range=(datetime_start, datetime_end))
    else:
        qs =  Entry.objects.filter(user=request.user)
    avg_speed = qs.aggregate(Avg('speed'))['speed__avg']
    avg_speed = avg_speed and round(avg_speed, 2)
    entries = qs.values('id','datetime','distance','duration')
    
    context = {'entries': entries, 'avg_speed': avg_speed, 'form':form}
    return render(request, 'statistic/entry_list.html', context)

report_page/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}

<!--Login-->
<div class="container py-5">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {{ login_form }}
        <button class="btn btn-primary" type="submit">Login</button>
    </form>
    <p class="text-center">Don't have an account? <a href="{% url 'accounts:signup' %}">Create an account</a></p>
</div>

{% endblock %}

report_page/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}

<!--Register-->
<div class="container py-5">
	<h1>Sign Up</h1>
	<form method="POST">
		{% csrf_token %}
		{{ signup_form }}
		<button class="btn btn-primary" type="submit">Sign Up</button>
	</form>
	<p class="text-center">If you already have an account, <a href="{% url 'accounts:login' %}">login</a> instead.</p>
</div>

{% endblock %}

report_page/statistic/templates/statistic/entry_create.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<h1>Create</h1>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-primary" type="submit">Submit</button>
</form>
</div>
{% endblock %}

report_page/statistic/templates/statistic/entry_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h1>Create</h1>
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-warning" type="submit">Update</button>
    <a href="{% url 'statistic:delete' id=entry.id %}" role="button" class="btn btn-danger btn-block">Delete</a>
  </form>
</div>
{% endblock %}

report_page/statistic/templates/statistic/entry_list.html
{% extends 'base.html' %}
{% block content %}
<!-- list of entries  -->
{% if user.is_authenticated %}
<a role="button" class="btn btn-primary btn-lg" href="{% url 'statistic:create_entry' %}">Create</a>
<div class="container">
    <form method="POST" action="{% url 'statistic:index' %}">
      {% csrf_token %}
      {{form}}
      <button class="btn btn-primary btn-lg" type="submit">Filter</button>
    </form>
  </div>
<div>
    <h4 class="text-center mb-3 mt-3">Entries List. Average speed: {{avg_speed}}</h4>
    <div class="table-responsive-lg">
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Datetime</th>
                    <th scope="col">Distance</th>
                    <th scope="col">Duration</th>
                    <th scope="col">View</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for entry in entries %}
                <tr>
                    <td>{{entry.datetime}}</td>
                    <td>{{entry.distance}}</td>
                    <td>{{entry.duration}}</td>
                     <td>
                        <a role="button" class="btn btn-sm btn-outline-success"
                            href="{% url 'statistic:entry_detail' id=entry.id %}">View</a>
                    </td>
                    <td>
                        <a role="button" class="btn btn-sm btn-outline-danger"
                            href="{% url 'statistic:delete' id=entry.id %}">Delete</a>
                    </td>
                </tr>
                {%empty%}

                <span class="text-center">No entries</span>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{%else%}
<p>README page</p>
{% endif %}
{% endblock %}

report_page/statistic/templates/statistic/weekly.html
{% extends 'base.html' %}
{% block content %}
<!-- list of entries  -->
{% if user.is_authenticated %}
<div>
    <h4 class="text-center mb-3 mt-3">Weekly stats</h4>
    <div class="table-responsive-lg">
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Week</th>
                    <th scope="col">Total entries</th>
                    <th scope="col">Total distance</th>
                    <th scope="col">Total duration</th>
                    <th scope="col">Average Speed</th>
                </tr>
            </thead>
            <tbody>
                {% for entry in stats %}
                <tr>
                    <td>{{entry.week}}</td>
                    <td>{{entry.total_entries}}</td>
                    <td>{{entry.total_distance}}</td>
                    <td>{{entry.total_duration}}</td>
                    <td>{{entry.avg_speed}}</td>
                </tr>
                {%empty%}
                <span class="text-center">No stats</span>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{%else%}
<p>README page</p>
{% endif %}
{% endblock %}

report_page/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>Entries</title>
</head>

<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'statistic:index' %}">Report Page</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'statistic:weekly' %}">Weekly statistic</a>
                    </li>
                   
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
                    </li>
                    {%endif%}
                </ul>
            </div>
        </div>
    </nav>
    <div id="content">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>
</body>

</html>